"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
const GxDownloadScene_1 = __importDefault(require("./gxcore/script/scene/GxDownloadScene"));
const GxFirstScene_1 = __importDefault(require("./gxcore/script/scene/GxFirstScene"));
const TestSceneGameUI_1 = __importDefault(require("./script/TestSceneGameUI"));
/*
* 游戏初始化配置;
*/
class GameConfig {
    constructor() { }
    static init() {
        var reg = Laya.ClassUtils.regClass;
        reg("gxcore/script/scene/GxDownloadScene.ts", GxDownloadScene_1.default);
        reg("gxcore/script/scene/GxFirstScene.ts", GxFirstScene_1.default);
        reg("script/TestSceneGameUI.ts", TestSceneGameUI_1.default);
    }
}
GameConfig.width = 1280;
GameConfig.height = 720;
GameConfig.scaleMode = "fixedheight";
GameConfig.screenMode = "horizontal";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "GxFirstScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;
exports.default = GameConfig;
GameConfig.init();
