/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GxDownloadScene from "./gxcore/script/scene/GxDownloadScene"
import GxFirstScene from "./gxcore/script/scene/GxFirstScene"
import PanelGameFail from "./PanelGameFail"
import PanelFrist from "./PanelFrist"
import PanelGameRun from "./PanelGameRun"
import PanelGameWin from "./PanelGameWin"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="GxDownloadScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("gxcore/script/scene/GxDownloadScene.ts",GxDownloadScene);
        reg("gxcore/script/scene/GxFirstScene.ts",GxFirstScene);
        reg("PanelGameFail.js",PanelGameFail);
        reg("PanelFrist.js",PanelFrist);
        reg("PanelGameRun.js",PanelGameRun);
        reg("PanelGameWin.js",PanelGameWin);
    }
}
GameConfig.init();