"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
const GxDownloadScene_1 = __importDefault(require("./gxcore/script/scene/GxDownloadScene"));
const GxFirstScene_1 = __importDefault(require("./gxcore/script/scene/GxFirstScene"));
const PanelGameFail_1 = __importDefault(require("./PanelGameFail"));
const PanelFrist_1 = __importDefault(require("./PanelFrist"));
const PanelGameRun_1 = __importDefault(require("./PanelGameRun"));
const PanelGameWin_1 = __importDefault(require("./PanelGameWin"));
/*
* 游戏初始化配置;
*/
class GameConfig {
    constructor() { }
    static init() {
        var reg = Laya.ClassUtils.regClass;
        reg("gxcore/script/scene/GxDownloadScene.ts", GxDownloadScene_1.default);
        reg("gxcore/script/scene/GxFirstScene.ts", GxFirstScene_1.default);
        reg("PanelGameFail.js", PanelGameFail_1.default);
        reg("PanelFrist.js", PanelFrist_1.default);
        reg("PanelGameRun.js", PanelGameRun_1.default);
        reg("PanelGameWin.js", PanelGameWin_1.default);
    }
}
GameConfig.width = 720;
GameConfig.height = 1280;
GameConfig.scaleMode = "fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "GxDownloadScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;
exports.default = GameConfig;
GameConfig.init();
